### ISSUE TITLE
Causes errors on non angular inputs

### ISSUE THREAD

**Issue by stuaxo** [luisfarzati/ng-bs-daterangepicker#20]
I'm using this with django, when I enable it I get lots of errors like this

```
    at http://192.168.56.101:8000/static/angular/angular.js:78:12
    at getControllers (http://192.168.56.101:8000/static/angular/angular.js:6141:19)
    at nodeLinkFn (http://192.168.56.101:8000/static/angular/angular.js:6312:35)
    at compositeLinkFn (http://192.168.56.101:8000/static/angular/angular.js:5722:15)
    at nodeLinkFn (http://192.168.56.101:8000/static/angular/angular.js:6305:24)
    at compositeLinkFn (http://192.168.56.101:8000/static/angular/angular.js:5722:15)
    at compositeLinkFn (http://192.168.56.101:8000/static/angular/angular.js:5725:13)
    at publicLinkFn (http://192.168.56.101:8000/static/angular/angular.js:5627:30)
    at http://192.168.56.101:8000/static/angular/angular.js:1343:27
    at Scope.$eval (http://192.168.56.101:8000/static/angular/angular.js:12075:28) <input type="hidden" name="csrfmiddlewaretoken" value="3JbQh7yANXJmrYWCA8ZeiI4ocKOk1yki"> 
```

That other input is nothing to do with the one I want the datepicker on.

**Comment by alanjames1987** [comment]
It appears this issue has been solved. If you're still experiencing this in the newest version please feel free to reopen this issue.
